//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TrackEye.rc
//
#define IDSAVE                          2
#define IDClosePupilCalib               3
#define IDSTART                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TRACKEYE_DIALOG             102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_TRACKINGSETTINGS_DIALOG     104
#define IDC_NImagesText                 105
#define IDC_NEigensText                 106
#define IDC_EyeDatabaseText             107
#define IDD_USBCAM_DIALOG               108
#define IDR_MAINFRAME                   128
#define IDR_TRACKEYE                    129
#define IDD_PCADIALOG                   130
#define IDB_ZS                          133
#define IDD_CALIBRATION4PUPIL           140
#define IDD_CameraFrame4Eye             142
#define IDD_2DTRAJECTORYEXTRACTOR       143
#define IDR_TRAJECTORY                  144
#define IDI_EXIT                        147
#define IDI_START                       148
#define IDI_CAM2                        150
#define IDI_SETTINGS                    153
#define IDI_CAM1                        155
#define IDI_STOP                        156
#define IDI_UPDATE                      157
#define IDD_EYEDATABASE                 158
#define IDI_EYE1                        159
#define IDD_PROGRAM_COLORS              160
#define IDI_EXPLORE                     172
#define IDR_DATABASE                    173
#define IDI_SAVE                        174
#define IDI_UR                          176
#define IDD_CALIBRATION4SNAKE           177
#define IDI_EYE2                        179
#define IDI_DELETE                      180
#define IDI_OK                          181
#define IDI_RECORD                      183
#define IDI_STOPRECORD                  184
#define IDI_AVI                         185
#define IDD_FILENAMEDLG                 186
#define IDC_DBdirectory                 1000
#define IDC_STATUS                      1001
#define IDSave2DB                       1002
#define IDC_NImages                     1003
#define IDC_DBdirectory2                1003
#define IDC_NeigenEyes                  1004
#define IDUpdateRectangle               1006
#define IDC_imgWidth                    1008
#define IDC_imgHeight                   1009
#define IDC_imgWidth2                   1010
#define IDC_imgHeight2                  1011
#define IDC_DBUpdateFrame               1013
#define IDC_imgWT                       1014
#define IDC_IMGHT                       1015
#define IDC_RECWT                       1016
#define IDC_RECHT                       1017
#define IDC_CHECK1                      1019
#define IDC_CHECK2                      1020
#define IDC_CHECK3                      1032
#define IDC_CHECK5                      1033
#define IDC_CHECK7                      1034
#define IDC_CHECK6                      1035
#define IDC_EyeTrackingFrame            1036
#define IDC_EYEFRAME                    1037
#define IDC_SPIN1                       1038
#define IDC_SPIN2                       1039
#define IDC_EDIT1                       1039
#define IDC_BUTTON1                     1040
#define IDC_CannyLower                  1041
#define IDC_BUTTON2                     1041
#define IDC_CannyUpper                  1042
#define IDC_BUTTON3                     1042
#define IDC_CannyApertureSize           1043
#define IDC_BUTTON4                     1043
#define IDR_StartTracking               1044
#define IDC_Alpha                       1044
#define IDC_BUTTON5                     1044
#define IDR_StartTracking2              1045
#define IDC_Beta                        1045
#define IDC_BUTTON6                     1045
#define IDR_EXITPROGRAM                 1046
#define IDC_Gamma                       1046
#define IDC_nPoints                     1047
#define IDC_EDIT2                       1048
#define IDC_iterations                  1048
#define IDC_EDIT3                       1049
#define IDC_UpdateRectangle             1050
#define IDC_HUEw                        1051
#define IDC_HUEh                        1052
#define IDC_DefineHUE                   1053
#define IDC_SaveHUE                     1054
#define IDC_Error                       1056
#define IDC_MaxError                    1057
#define IDC_RatioText                   1058
#define IDC_RatioEdit                   1059
#define IDC_ComponentText               1062
#define IDC_LEYEDIST                    1063
#define IDC_REYEDIST                    1064
#define IDC_STATIC_OUTPUT               1065
#define IDC_LeftX                       1067
#define IDC_LeftY                       1068
#define IDC_RightX                      1069
#define IDC_RightY                      1070
#define IDC_COMBO1                      1070
#define IDC_RADIO1                      1071
#define IDC_LeftPupilX                  1071
#define IDC_RADIO2                      1072
#define IDC_RightPupilX                 1072
#define IDC_RADIO3                      1073
#define IDC_LeftPupilY                  1073
#define IDSavePupilCalib                1074
#define IDC_RightPupilY                 1074
#define IDC_RADIO4                      1074
#define IDC_ThresholdSettings           1075
#define IDC_LeftPupilRadius             1075
#define IDC_COMBO2                      1075
#define IDC_thresholdValue              1076
#define IDC_RightPupilRadius            1076
#define IDC_RADIO5                      1076
#define IDC_sampleFilename              1077
#define IDC_LeftPupilLocation           1077
#define IDC_blockSize                   1077
#define IDC_RADIO6                      1077
#define IDC_originaltext                1078
#define IDC_RightPupilLocation          1078
#define IDC_colorspacetext              1079
#define IDC_edgestext                   1080
#define IDC_finaltext                   1081
#define IDTEST                          1082
#define IDC_CameraFrame4Eye             1083
#define IDC_thresholdedtext             1083
#define IDEXIT                          1084
#define IDC_sumcolorspace               1085
#define IDC_sumcomponent                1086
#define IDC_sumbinthreshold             1087
#define IDC_sumbinthresholdvalue        1088
#define IDC_SLIDER_L                    1088
#define IDC_sumcanny                    1089
#define IDC_SLIDER_R                    1089
#define IDC_Trajectory                  1090
#define IDC_circleAlgorithm             1090
#define IDC_ExtractTrajectory           1091
#define IDC_EyeTrackerSettings          1092
#define IDC_EDITLPX                     1093
#define IDC_EDITLPY                     1094
#define IDC_DeletesampleEye             1094
#define IDC_EDITLPR                     1095
#define IDC_EDITRPX                     1096
#define IDC_EDITRPY                     1097
#define IDC_EDITRPR                     1098
#define IDC_EDITLEX                     1099
#define IDC_EDITLEY                     1100
#define IDC_EDITREX                     1101
#define IDC_EDITREY                     1102
#define IDC_ClearHT                     1103
#define IDC_PROGRESS1                   1106
#define IDC_SLIDERXplane                1107
#define IDC_SLIDERYplane                1108
#define IDC_FirstFrame                  1108
#define IDC_SaveObjectColor             1109
#define IDC_TrackObject                 1110
#define IDC_AVI                         1111
#define IDC_AVITRAJECTORY               1112
#define IDC_NextFrame                   1113
#define IDEXITRAJECTORY2D               1114
#define IDC_STATUSCONSOLE               1115
#define IDC_ComponentEdit               1116
#define IDC_COMBOColorspace             1117
#define IDC_UpdayeEyeDatabase           1119
#define IDC_EYE1                        1120
#define IDC_EYE2                        1121
#define IDC_EYE3                        1122
#define IDC_EYE4                        1123
#define IDC_EYE5                        1124
#define IDC_EYE6                        1125
#define IDC_EYE7                        1126
#define IDC_EYE8                        1127
#define IDC_EYE9                        1128
#define IDC_EYE10                       1129
#define IDC_EYE11                       1130
#define IDC_EYE12                       1131
#define IDC_EYE13                       1132
#define IDC_EYE14                       1133
#define IDC_EYE15                       1134
#define IDC_EYE16                       1135
#define IDC_EYE17                       1136
#define IDC_EYE18                       1137
#define IDC_EYE19                       1138
#define IDC_EYE20                       1139
#define IDC_CLOSEEYEDATABASE            1140
#define IDC_Directory                   1142
#define IDC_CHECK4                      1144
#define IDC_RGB1                        1145
#define IDC_RGB2                        1146
#define IDC_RGB3                        1147
#define IDC_RGB4                        1148
#define IDC_CHOOSEDIRECTORY             1149
#define IDC_CHECK8                      1149
#define IDC_CHOOSEDIRECTORY2            1150
#define IDC_CHECK9                      1150
#define IDC_CHOOSEDIRECTORY1            1151
#define IDC_RGB5                        1151
#define IDC_EYETEXT                     1152
#define IDC_RGB6                        1152
#define IDC_BLINKTEXT                   1153
#define IDC_DONE                        1154
#define IDEXITDB                        1155
#define IDC_DBwindow                    1156
#define IDC_BLINKSTATUS                 1157
#define IDC_LoggingStatus               1158
#define IDC_FPS                         1159
#define IDC_SnakeSettings               1160
#define IDC_RGNL                        1161
#define IDC_CLRSPC                      1162
#define IDC_THRSHLD                     1163
#define IDC_DGDTCTN                     1164
#define IDC_FNL                         1165
#define IDSaveSnakeCalib                1166
#define IDC_TESTSETTINGS                1167
#define IDC_DELETE                      1168
#define IDC_RECORD                      1169
#define IDC_STOPRECORD                  1170
#define IDC_numOfRecorded               1171
#define IDC_RECORDTEXT                  1172
#define IDC_VARIANCEEDIT                1173
#define IDC_WRITE2AVI                   1173
#define IDC_VARIANCETEXT                1174
#define IDC_RADIO_EYE                   1176
#define IDC_TEMPMATCHING                1178
#define IDC_RADIOSOURCE                 1179
#define IDC_SELECTFILE                  1180
#define IDC_RADIO_FACE                  1181
#define ID_TRACKEYEMENU_PCASETTINGS     32774
#define ID_HELP_ABOUTTRACKEYE           32775
#define ID_TRACKEYEMENU_FACETRACKERSETTINGS 32776
#define ID_TRACKEYEMENU_ADJUSTCAPTUREDEVICESETTINGS 32777
#define ID_TRACKEYEMENU_EXIT            32778
#define ID_SETTINGS_SELECTFILE          32779
#define ID_DATABASE_EXPLOREDATABASE     32781
#define ID_TRACKEYEMENU_STARTTRACKING   32782
#define ID_TRACKEYEMENU_STOPTRACKING    32783
#define ID_TRACKEYEMENU_SELECTPROGRAMCOLORS 32784
#define ID_DATABASEOPERATIONS_UPLOADEYEDATABASE 32785
#define ID_DATABASEOPERATIONS_UPDATEBLINKDATABASE 32786
#define ID_DATABASEOPERATIONS_EXIT      32787
#define ID_HELP_SHOWTRACKEYEHELPFILE    32789
#define ID_DATABASE_CLEARDATABASE       32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1182
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
